### ISSUE TITLE
A dumb question: Can we add html tags and or change/set CSS dynamically from rust during runtime?

### ISSUE THREAD

**Issue by shujaatak** [bamilab/browser-window#3]
Browser-Window seems promising but before diving in it full time, I really want to know if it is possible to modify UI from rust side in runtime.

Also, I want to know that if a user clicks on a specific Button then is there any way to receive that event and recognize that specific Button click in rust side?

If YES! Then door is wide open for start using Browser-Window! Actually I am searching for functionality more or less like https://github.com/sciter-sdk/rust-sciter

**Comment by bamidev** [comment]
I mean, technically speaking this should be possible. Currently the way to do it would be to execute JS from rust. The JS is executed client-side, and you can have it execute JS that changes the DOM.

In the other direction, from within JS you can call the `invoke_extern` function, which passes back some values as strings: https://github.com/bamidev/browser-window/blob/e62f9a765e3485ef538efef1a69cd90b54089c66/examples/terminal.rs#L93

**Comment by bamidev** [comment]
But the code has become a bit out of date. Will update it to work with the latest CEF version soon. But you can always use the old CEF 87.
