### ISSUE TITLE
the browser-window on macos outdate

### ISSUE THREAD

**Issue by RyanWongGithub** [bamilab/browser-window#4]
the libcef.dylib on macos called "Chromium Embedded Framework.framework, but browser-window still requires "libcef.dylib".

**Comment by bamidev** [comment]
I have not added MacOS support. I have no mac so I have zero knowledge on what is needed to make it work on it.

Hopefully someone wants to fix that for me.

**Comment by bamidev** [comment]
But if you can make it work and put an PR up I'd merge it.
